
-- EXERCICIO 01
SELECT LAST_NAME, HIRE_DATE, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME = INITCAP('&&v_ei'))
AND LAST_NAME != INITCAP('&v_ei')
ORDER BY HIRE_DATE;

undefine v_ei;

-- EXERCICIO 02
SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY >= (SELECT AVG(SALARY) FROM EMPLOYEES)
ORDER BY SALARY DESC;


-- EXERCICIO 03
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE ('%u%') OR LAST_NAME LIKE ('U%') OR LAST_NAME LIKE ('%u'));

-- EXERCICIO 04
SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID FROM EMPLOYEES E
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID = 1700);

-- EXERCICIO 04 - VERSÃO 2
SELECT E.LAST_NAME, E.DEPARTMENT_ID, E.JOB_ID FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.LOCATION_ID = 1700;


-- EXERCICIO 05
SELECT LAST_NAME, SALARY FROM EMPLOYEES 
WHERE MANAGER_ID = (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King'); 


-- EXERCICIO 06
SELECT DEPARTMENT_ID, LAST_NAME, JOB_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Executive');


-- Exericio 07
SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES) 
AND DEPARTMENT_ID IN 
(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LOWER(LAST_NAME) LIKE ('%u%'));

