

-- EXERCICIO 02
SELECT COUNTRY_ID CO, COUNTRY_NAME FROM COUNTRIES
MINUS
SELECT C.COUNTRY_ID CO, COUNTRY_NAME FROM COUNTRIES C
JOIN LOCATIONS L
ON C.COUNTRY_ID = L.COUNTRY_ID
JOIN DEPARTMENTS D
ON L.LOCATION_ID = D.LOCATION_ID;



-- EXERCICIO 04
SELECT EMPLOYEE_ID E, JOB_ID JI FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID, JOB_ID FROM JOB_HISTORY;


